title: Naveen Vinayak S
#logo: /assets/img/naveen_head_circle.png
#show_downloads: true
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
show_footer_attribution: false
github:
  is_project_page: false
  #is_user_page: true # View My GitHub Profile
